### ISSUE TITLE
bosh cli breaks when cf-uuac gems are in the same gemfile

### ISSUE THREAD

**Issue by spm2jthykatt** [cloudfoundry-community/jumpbox-boshrelease#1]
Comparing v3 and v2, prepackaging scripts for gems in jumpbox v3 and v2 are successful, however, when running bosh cli with v3, I get the following errors:
```
bundle install -binstubs
cd ./bin
./bosh
/usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2922.0/bin/bosh:6:in `<top (required)>': uninitialized constant Bosh (NameError)
	from ./bosh:16:in `load'
	from ./bosh:16:in `<main>'
```

The workaround I have done so far is to remove the cf-uuac from the v3 gemfile. However, I don't get cf-uaac with this.

When using the gemfile and gemfile.lock from v2, I do not get the errors. 

Any help greatly appreciated.
![scrn1](https://cloud.githubusercontent.com/assets/12942332/8218359/0f94ffa8-1508-11e5-8404-ad4e973751fb.png)

**Comment by longnguyen11288** [comment]
fixed
