### ISSUE TITLE
Safe downloading redirect instead of binary

### ISSUE THREAD

**Issue by krutten** [cloudfoundry-community/jumpbox-boshrelease#17]
Safe url was changed from jhunt/safe to starkandwayne/safe but the CI setting.yml still references the  old name resulting in the download of a 1248 redirect JSON file instead.

Need to correct the concourse file and have it upload new blobs

**Comment by jhunt** [comment]
Fixed in #18

**Comment by jhunt** [comment]
Changing the github org didn't fix anything.  Now it's just downloading the redirect from the `starkandwayne` org.  Will continue investigating.

**Comment by jhunt** [comment]
Fixed with a bump to save version (had a bug fix anyway)
