### ISSUE TITLE
libcurl issues

### ISSUE THREAD

**Issue by jhunt** [cloudfoundry-community/jumpbox-boshrelease#19]
There is either something wrong with the libcurl package, or the way the LD_LIBRARY_PATH is being sourced.  We are getting these errors trying to do things with curl on jumpboxen:

```
curl: /var/vcap/packages/jumpbox/lib/libcurl.so.4: no version information available (required by curl)
```

Fix the package so that this sort of error stops.

**Comment by bonzofenix** [comment]
I encounter this too on version 4.5.2. This is how it can be fix manually:
 https://stackoverflow.com/questions/30017397/error-curl-usr-local-lib-libcurl-so-4-no-version-information-available-requ

**Comment by jhunt** [comment]
@bonzofenix what stemcell are you on?  I'm not seeing this on Xenial stemcells.

**Comment by RMeharg** [comment]
I am also seeing this issue on 4.6.0 xenial stemcell 315.13.

**Comment by jhunt** [comment]
Excellent (that it is reproducible, not that you are encountering the issue still).  I'll take Xenial 315.x for a spin.

**Comment by jhunt** [comment]
Okay, the main problem is that the issue shows up because of `git`, not because of `curl` itself:

```
$ ldd /var/vcap/packages/jumpbox/libexec/git-core/git-remote-https
/var/vcap/packages/jumpbox/libexec/git-core/git-remote-https: /var/vcap/packages/jumpbox/lib/libcurl.so.4: no version information available (required by /var/vcap/packages/jumpbox/libexec/git-core/git-remote-https)
	linux-vdso.so.1 =>  (0x00007ffd8ef6c000)
	libcurl.so.4 => /var/vcap/packages/jumpbox/lib/libcurl.so.4 (0x00007f67487fd000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f67485e3000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f67483db000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f67481be000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6747df4000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f6747b8b000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f6747746000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6748a74000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6747542000)
```

Both are linked against `libcurl.so.4`, but `git-remote-https` seems to want the 4.3.0 version on the system, and `curl` wants the 4.5.0 version in the packages.  `LD_LIBRARY_PATH` is being set to favor 4.5.0, which causes git consternation.

I believe the easiest fix is to repackage git against the same libcurl; maybe via package dependencies.

**Comment by jhunt** [comment]
Given https://github.com/cloudfoundry-community/containers-boshrelease/pull/1, I'm going to close this.  Docker is a way better vehicle for jumpboxen.
