### ISSUE TITLE
Add credhub cli, fly cli, and GO environment

### ISSUE THREAD

**Issue by amuessig** [cloudfoundry-community/jumpbox-boshrelease#50]
I would like to have the following cli's on the jumpbox:
* Credhub CLI
* Fly CLI

Furthermore, a GO package would be great!

Thanks

**Comment by jhunt** [comment]
What would the GO package do?

**Comment by amuessig** [comment]
It's just for compiling and running tools written in GO.

**Comment by jhunt** [comment]
So you just want the golang runtime.  👍

**Comment by benjaminguttmann-avtq** [comment]
I started adding fly and credhub cli in PR #59
