### ISSUE TITLE
sudoers option

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry-community/jumpbox-boshrelease#58]
some users don't need sudoers permission.
Would you set sudoers option with jumpbox user spec?

**Comment by jhunt** [comment]
Yes.

https://github.com/cloudfoundry-community/jumpbox-boshrelease/blob/master/jobs/jumpbox/templates/bin/watcher#L248

If you set `sudo: false` in the users definition in the list of jumpbox users, they wont get sudo.  By default, everyone gets sudo.
