### ISSUE TITLE
Add `certstrap` utility

### ISSUE THREAD

**Issue by jhunt** [cloudfoundry-community/jumpbox-boshrelease#6]
The Genesis Cloud Foundry template deployment uses `certstrap`.  It would be nice to have it available on the jumpbox.

**Comment by 7hunderbird** [comment]
We are unable to find in the https://github.com/jhunt/jumpbox that it installs it.  Are we not going to add it to jumpbox?

**Comment by jhunt** [comment]
This still needs to happen in the jumpbox BOSH release

**Comment by jhunt** [comment]
Although, given that certstrap doesn't make binary releases available, we may just replace the certstrap usage with openssl usage.  Certs aren't _that_ hard...
