### ISSUE TITLE
Add OpenJDK to jumpbox

### ISSUE THREAD

**Issue by amuessig** [cloudfoundry-community/jumpbox-boshrelease#60]
Hey,

are there plans to add OpenJDK to the jumpbox boshrelease? We have need for this. Ideally, this is an optional parameter, so that it is not installed on every jumpbox.

**Comment by jhunt** [comment]
We actually have plans to do something completely different, leveraging Docker for the toolset space.  At that point, you can craft your own docker image that has just what you want / need in it.  The PR for this new way of doing things is #61

**Comment by daviddob** [comment]
In the interim, if you are looking to add the Java JDK to a jumpbox deployment you can colocate [this Java JDK bosh-release](https://github.com/making/openjdk-boshrelease) in the deployment to add the required packages.
