### ISSUE TITLE
Add bbr cli

### ISSUE THREAD

**Issue by gdenn** [cloudfoundry-community/jumpbox-boshrelease#71]
hi,

since bbr became the canonical way of doing backups of bosh deployments and directors, could we include the binary in the jumpbox release by default?

best,
D

**Comment by benjaminguttmann-avtq** [comment]
@jhunt : I could prepare a PR for this if it is okay from your side to add it

**Comment by jhunt** [comment]
Go for it!  I always enjoy reviewing a PR.

**Comment by benjaminguttmann-avtq** [comment]
@jhunt : Here you go :)

**Comment by gdenn** [comment]
@jhunt @benjaminguttmann-avtq thats great! :)
