### ISSUE TITLE
Add cf/uaac to blobs that are updated via CI

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/jumpbox-boshrelease#8]
http://ci.vsphere.starkandwayne.com/pipelines/jumpbox-boshrelease?groups=blobs

**Comment by jhunt** [comment]
CF CLI is good.  UAAC is a gem, so I think the user provisioning gets that.  Will test today with 4.1.5 and then get back to this ticket.

**Comment by jhunt** [comment]
Fixed!  Whee!
