### ISSUE TITLE
Update CF CLI to latest version via CI pipeline

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-community/jumpbox-boshrelease#9]
Update the blob for the `cf` package in this boshrelease to use [v6.20.0 of the cf cli](https://github.com/cloudfoundry/cli/releases/tag/v6.20.0).

**Comment by givett** [comment]
Updated the blob for the cf package to use v6.20.0 of the cf cli.

**Comment by jhunt** [comment]
Can / should we do this via Pipeline?

**Comment by geofffranks** [comment]
That was the intention

**Comment by jhunt** [comment]
Hah, looks like #8 beat you to the punch
