### ISSUE TITLE
packaging: line 35: cd: git-2.35.1: No such file or directory

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry-community/jumpbox-boshrelease#95]
Hi, in the last release there is a typo, you updated git to .7 but switch to the .1 folder there. 

https://github.com/cloudfoundry-community/jumpbox-boshrelease/commit/e3af8002291f726c9994486335f317f4db445bcd#diff-f7f61ed11e03fe8b74110ee483eed567b47eafc49035a168b2ff9b8b03549cb6L35

Renaming the folder should fix that

**Comment by ramonskie** [comment]
ughhh i fell like an idiot :(
